title: Some thoughts
author: Gustavo Villalta
email: gvillalta99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog about technology and other things.
# social links
twitter_username: gvillalta99
github_username:  gvillalta99

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal